language: generic
dist: bionic
global:
  - CLIVERSION=0.7.2
matrix:
  include:
    - env:
        - BOARD="xiao"
    - env:
        - BOARD="wio_terminal"

before_install:
  - sudo apt-get install --reinstall python3-pip
  - python3 -m pip install
  - sudo apt-get install python3-setuptools
install:
  - pip3 install ardupy-aip
  - aip

script: 
  - echo "CI Test"
  - aip install  Seeed-Studio/seeed-ardupy-TFLidar.git
  - aip build --board=$BOARD
  
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always